FROM mcr.microsoft.com/devcontainers/typescript-node:0-18
RUN npm install -g ts-node nodemon
RUN wget https://downloads.mongodb.com/compass/mongodb-mongosh_1.10.1_amd64.deb && sudo apt install ./mongodb-mongosh_1.10.1_amd64.deb